server {
    listen 80;

    # Frontend
    location / {
        root /var/www/html;
        index index.html;
    }

    # Login microservice
    location /api/login {
        proxy_pass http://52.73.46.11:3000/login;
    }

    # Register microservice
    location /api/register {
        proxy_pass http://54.147.90.33:3001/register;
    }

    # Roles microservice
    location /api/roles {
        proxy_pass http://3.87.123.45:3002/roles;
    }
    location /api/register-pet {
    proxy_pass http://<IP_REGISTER_PET>:3004/register-pet;
}

location /api/medical/ {
    proxy_pass http://<IP_MEDICAL_UPDATE>:3005/medical/;
}

}
